language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
sudo: false
before_script:
- npm install grunt grunt-cli grunt-contrib-jshint grunt-contrib-csslint grunt-phplint --save-dev
- mysql -u root -e "CREATE DATABASE rhymix"
- mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis')"
- php -S localhost:8000 &
- wget http://codeception.com/releases/2.1.11/codecept.phar
script:
- php codecept.phar build
- php codecept.phar run -d --fail-fast --env travis
- grunt lint
notifications:
  email: false
